# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='quiz',
            field=models.CharField(default='hahaha', max_length=500),
            preserve_default=False,
        ),
    ]
