# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170208_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptQuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('data', django_mysql.models.DynamicField()),
                ('attempt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.AttemptModel')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.QuestionModel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
