# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20170315_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmatchingmodel',
            name='listA',
            field=django_mysql.models.ListCharField(models.CharField(max_length=255), blank=True, max_length=255, size=None),
        ),
        migrations.AlterField(
            model_name='wordmatchingmodel',
            name='listB',
            field=django_mysql.models.ListCharField(models.CharField(max_length=255), blank=True, max_length=255, size=None),
        ),
    ]
