# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_multiplechoicemodel_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplechoicemodel',
            name='position',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
    ]
