# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170315_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordmatchingmodel',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
