# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attemptquestionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderQuestionModel',
            fields=[
                ('questionmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.QuestionModel')),
                ('information', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('app.questionmodel',),
        )
    ]
