# LOCAL USE ONLY. Exposes sshd of the web to the local machine.

version: '2'

volumes:
  db-data:
    driver: local

services:
 nginx:
  image: nginx:mainline-alpine
  volumes:
    - .:/code
    - ./config/nginx:/etc/nginx/conf.d
    - ./static:/static
  ports:
    - "8000:8000"
  depends_on:
    - web
 db:
   image: mariadb
   restart: always
   env_file: .env
   volumes:
    - db-data:/var/lib/mysql
   # Expose port 33060 for external MySQL clients
   ports:
    - "33060:3306"
 web:
   build:
     context: .
     dockerfile: web-dev.Dockerfile
   restart: always
   env_file: .env
   volumes:
     - .:/code
     - ./static:/static
   depends_on:
     - db
   expose:
     - "8000"
   ports:
     - "2222:22"