version: '2'

volumes:
  db-data:
    driver: local

services:
 db:
   image: mariadb
   restart: always
   env_file: .env
   volumes:
    - db-data:/var/lib/mysql
   ports:
    - "33060:3306"
 web:
   build: .
   restart: always
   env_file: .env
   volumes:
     - .:/code
   ports:
     - "8000:8000"
   depends_on:
     - db
   links:
     - db